### ISSUE TITLE
Document Pry Workflow

### ISSUE THREAD

**Issue by rking** [hopsoft/pry-test#5]
In the wiki + link to from README, please.

I'm really into this stuff, I want to see what you've got.

Here's my overall vision: https://github.com/pry/pry/wiki/pry-de
And here's a tool I've been using to make that work: https://github.com/ConradIrwin/pry-rescue/blob/master/lib/pry-rescue/minitest.rb

BTW, perhaps you can use the [showterm](http://showterm.herokuapp.com/) gem to make a demo? I'd really appreciate it. Here are a couple we made of earlier pry-rescue things:

http://showterm.io/ba798d63ac1d24c0db8bf
http://showterm.io/5dfdc641a558cdb1eabb0

I'm excited about your work!

**Comment by hopsoft** [comment]
I'll be adding a tutorial video soon.
